In [1]:
import numpy as np

In [2]:
arr1 = np.arange(0,10)

In [3]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr2 = np.arange(10,20)

In [5]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
arrMatrix = [arr1, arr2]

In [7]:
arrMatrix

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [8]:
iMatrix = np.eye(5)

In [9]:
iMatrix

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [10]:
newMatrix = iMatrix/arr1

ValueError: operands could not be broadcast together with shapes (5,5) (10,) 

In [11]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1[0:3]

array([0, 1, 2])

In [13]:
arrNew = np.array([2,3,4,5])


In [14]:
arrNew

array([2, 3, 4, 5])

In [15]:
arr1[0:3]/arrNew

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [16]:
arr1/arrNew

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [17]:
arr1[0:3]/0.5

array([ 0.,  2.,  4.])

In [18]:
arr1[0:3]

array([0, 1, 2])

In [19]:
arr1[3:5]


array([3, 4])

In [20]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr3 = arr1

In [22]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr3[0] =55

In [24]:
arr3

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [25]:
arr1

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [26]:
myArr = np.arange(50)
myArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
myArr.reshape(10,5)
myArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
myArr = myArr.reshape(10,5)

In [29]:
myArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [30]:
myArr+= 1

In [31]:
myArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [32]:
myArr.T

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [33]:
myArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [34]:
myArr = myArr.T

In [35]:
myArr

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [36]:
myArr

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [40]:
from numpy.random import randn

In [41]:
myArr = randn(5,5)

In [42]:
myArr

array([[-1.71169536, -0.35196179, -0.90515833,  0.30657024,  1.01539708],
       [-1.14428125,  2.39240036,  1.29628761, -0.04852693,  0.30825071],
       [-1.49611126,  0.44022041, -0.14723934, -0.8788509 , -0.91454893],
       [-1.18281809,  1.36998344, -0.0890449 ,  0.56030192, -0.210313  ],
       [ 1.51345515,  0.71440031, -0.05137306,  0.82521906, -0.73023951]])

In [43]:
myArr.mean

<function ndarray.mean>

In [44]:
myArr.mean

<function ndarray.mean>

In [45]:
myArr.mean()

0.035212944017667509

In [46]:
myArr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [47]:
myArr.max()

2.3924003573073112

In [48]:
myArr.std()

1.009954537997561